### PR TITLE
Expand filter on projects to include more countries

### PR DESCRIPTION
**Pull request by d-team-nrc**
There may be more elegant ways to do this. Feel free to adjust as needed!

### CODE REVIEW

**Review by CarolErnst — COMMENTED** [review]
@taylordowns2000 NRC upgraded their OpenFn plan to Scale to support their global rollout, and needs to make a small change to the filter on projects to include different countries. Could you have a very quick look at the proposed change before we commit it?

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
At first glance, `DJ`, `ER`, `ET`... will all be undefined. Those aren't variables, they're strings. Also, `UG` appears twice. Can that be removed? Go with:
```js
['DJ', 'ER', 'ET', 'KE', 'SO', 'SS', 'TZ', 'UG', 'CO', 'NG', NO].indexOf(f.field1.substring(0,2)) === 0
```
More importantly, how was this change tested? In Node.js? Or with [openfn-devtools](https://github.com/openfn/openfn-devtools)? Either one should be fine for this case, as it's raw javascript you're testing, not the endpoint or the language-package. If it's producing the desired output, go for it.

**Comment by d-team-nrc** [comment]
Thanks for catching those late-night mistakes, @taylordowns2000!

I tested it in Chrome's Javascript console since it's a basic true/false. Would you recommend a better alternative to do this filter? I simply wanted to avoid 10 or operators!

I've also made sure 'NO' in single quotes, so this should be ready to use if you don't have further comments.
`['DJ', 'ER', 'ET', 'KE', 'SO', 'SS', 'TZ', 'UG', 'CO', 'NG', 'NO'].indexOf(f.field1.substring(0,2)) === 0`

**Comment by taylordowns2000** [comment]
I ran a quick test in Node and the code doesn't actually do what I think you wanted. (Return only those items with a field 1 values that starts with one of the strings in that list.) My code below returns the desired result (if I understand correctly) and looks quite a bit cleaner/more readable IMO. What do you think?

```js
const data = [
  {"field1": "KENYA"},
  {"field1": "NORWAY"},
  {"field1": "FOO"},
  {"field1": "BAR"},
  {"field1": "BAZ"}
]

const selected = ['DJ', 'ER', 'ET', 'KE', 'SO', 'SS', 'TZ', 'UG', 'CO', 'NG', 'NO'];

const filteredFinancials = data.filter(f => (
  selected.some(x => (f.field1.startsWith(x)))
));

console.log(filteredFinancials);
// [ { field1: 'KENYA' }, { field1: 'NORWAY' } ]
```
If the above makes sense, and is doing what you want it to do, you can drop in your test array (I'm calling mine `selected` but I'm terrible at naming—maybe `selectedCountries`?) as a const and then replace line 47 with `selected.some(x => (f.field1.startsWith(x)))`

**Comment by d-team-nrc** [comment]
Looks good. Please go ahead and make the change to master from your side if that's okay (not sure if I have access to that). And you can call the const "filteredCountries". Thanks!

**Comment by taylordowns2000** [comment]
addressed in #11

**Pull request closed without merging**
